title: Infectious Diseases Toolkit
# this appears in the html browser tab for the site title (seen mostly by search engines, not users)

description: "Find tools and guidelines to help you access, analyse and share infectious disease data, and respond quickly to disease outbreaks."
# Metadata description of the website

remote_theme: ELIXIR-Belgium/elixir-toolkit-theme@2.5.0

gtag: G-TNT17YGXQ4

theme_variables:
  privacy_statement_url: /about/privacy
  theme_color: 457B9D
  fonts:
    - https://fonts.googleapis.com/css2?family=PT+Sans:ital,wght@0,400;0,700;1,400;1,700&display=swap

exclude:
  - README.md
  - .gitignore
  - var/
  - vendor
  - Gemfile*
  - LICENSE

permalink: /:categories/:year/:month/:day/:title

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
      sidebar: main
  -
    scope:
      path: "about"
      type: "pages"
    values:
      sidebar: about
  -
    scope:
      path: "contribute"
      type: "pages"
    values:
      sidebar: contribute
      search_exclude: true
  -
    scope:
      path: "attributing-credit"
      type: "pages"
    values:
      type: attributing_credit
      datatable: true

  -
    scope:
      path: "data-analysis"
      type: "pages"
    values:
      type: data_analysis
      datatable: true
    
  -
    scope:
      path: "data-communication"
      type: "pages"
    values:
      type: data_communication
      datatable: true

  -
    scope:
      path: "data-description"
      type: "pages"
    values:
      type: data_description
      datatable: true

  -
    scope:
      path: "data-sources"
      type: "pages"
    values:
      type: data_sources
      datatable: true

  -
    scope:
      path: "ethical-legal-and-social-issues"
      type: "pages"
    values:
      type: ethical_legal_and_social_issues
      datatable: true

  -
    scope:
      path: "provenance"
      type: "pages"
    values:
      type: provenance
      datatable: true

  -
    scope:
      path: "quality-control"
      type: "pages"
    values:
      type: quality_control
      datatable: true

  -
    scope:
      path: "showcase"
      type: "pages"
    values:
      type: showcase
      datatable: true

  -
    scope:
      path: "national-resources"
      type: "pages"
    values:
      type: national_resources
      datatable: true

  -
    scope:
      path: "showcase/TEMPLATE-showcase.md"
      type: "pages"
    values:
      sitemap: false
      search_exclude: true
      no_robots: true

  -
    scope:
      path: "TEMPLATE-page.md"
      type: "pages"
    values:
      sitemap: false
      search_exclude: true
      no_robots: true

  -
    scope:
      path: "national-resources/TEMPLATE_resources.md"
      type: "pages"
    values:
      sitemap: false
      search_exclude: true
      no_robots: true
plugins:
  - elixir-toolkit-theme-plugins
  - jemoji
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-github-metadata
