name: Link Checker

on:
  repository_dispatch:
  workflow_dispatch:
  schedule:
    - cron: "00 18 * * *"

jobs:
  linkChecker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
            bundle install

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
          bundler-cache: true
          cache-version: 0

      - name: Build with Jekyll
          # Outputs to the './_site' directory by default
        run: |
            bundle exec jekyll build --baseurl "${{ steps.pages.outputs.base_path }}"
        env:
            PAGES_REPO_NWO: ${{ github.repository }}
            JEKYLL_BUILD_BRANCH: ${{ github.ref_name }}
            JEKYLL_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            JEKYLL_BASE_PATH: ${{ steps.pages.outputs.base_path }}

      - name: Link Checker
        id: lychee
        uses: lycheeverse/lychee-action@v1
        with:
            # Check all markdown, html and reStructuredText files in repo (default)
            args: --fallback-extensions .html  _site/
            # Don't fail action on broken links
            fail: false

      # Create or Update the issue based on the link check result
      - name: Update Comment From File
        uses: create-or-update-comment@v4
        with:
            comment-id: 2531398005
            title: Link Checker Report
            body-path: ./lychee/out.md
            labels: report, automated issue
